### ISSUE TITLE
[Question] 关于高效率的场景

### ISSUE THREAD

**Issue by lkqm** [fast-light/fastaop#2]
关于:” 继承此项目可以生成任何模板代码，提高日常编码体验和效率”, 有疑问？除了AOP，能否描述一个具体的场景

**Comment by ychost** [comment]
1. 可以在方法内部拿到方法的名字、参数、签名等数据，        
 @FastAspectVar FastAspectContext context = FastAspectContext.currentContext();
2. 可以继承此项目生成你业务需要的模板代码，fastapt 里面封装好了很多 javac 的方法，踩了很多坑
